name: Format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: black
        uses: lgeiger/black-action@master
        with:
          args: . --check --line-length 100
